//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: groceryList.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate GroceryList_GroceryListClient, then call methods of this protocol to make API calls.
internal protocol GroceryList_GroceryListClientProtocol {
  func get(_ request: GroceryList_Empty, callOptions: CallOptions?) -> UnaryCall<GroceryList_Empty, GroceryList_GroceryListReply>
}

internal final class GroceryList_GroceryListClient: GRPCClient, GroceryList_GroceryListClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the groceryList.GroceryList service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Sends a greeting.
  ///
  /// - Parameters:
  ///   - request: Request to send to get.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func get(_ request: GroceryList_Empty, callOptions: CallOptions? = nil) -> UnaryCall<GroceryList_Empty, GroceryList_GroceryListReply> {
    return self.makeUnaryCall(path: "/groceryList.GroceryList/get",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}

// Provides conformance to `GRPCPayload`
extension GroceryList_Empty: GRPCProtobufPayload {}
extension GroceryList_Item: GRPCProtobufPayload {}
extension GroceryList_GroceryListReply: GRPCProtobufPayload {}
